version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
  
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    command: ["start-dev"]
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak_network

networks:
  backend:
    driver: bridge
  keycloak_network:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
  
