POST http://localhost:8181/campaigns

{
    "Name": "testando 03",
    "Content": "change password",
    "emails": ["test", "test03@gmail.com"]
}

###
GET http://localhost:8181/campaigns/cq1dtodj8i9telddm0vg
